name: Nova Directory Validator

on:
  push:
  pull_request:

jobs:
  validate-dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate required files and dirs
        run: |
          REQUIRED=(
            "dependency.json"
            "commands"
            "plugins"
            "root.nv"
            "versions.json"
            "priorities.json"
            "extras"
          )

          # Check for missing
          missing=0
          for item in "${REQUIRED[@]}"; do
            if [ ! -e "$item" ]; then
              echo "❌ Missing: $item"
              missing=1
            else
              echo "✅ Found: $item"
            fi
          done

          # Check for unknown files/dirs at repo root
          unknown=0
          for entry in * .*; do
            case "$entry" in
              .|..|.git|.github) continue ;; # allowed hidden dirs
              ${REQUIRED[0]}|${REQUIRED[1]}|${REQUIRED[2]}|${REQUIRED[3]}|${REQUIRED[4]}|${REQUIRED[5]}|${REQUIRED[6]})
                continue ;;
              *)
                echo "⚠️ Unknown file/dir: $entry"
                unknown=1
                ;;
            esac
          done

          if [ $missing -eq 1 ] || [ $unknown -eq 1 ]; then
            echo "Validation failed: Repo contents don’t match the sacred layout."
            exit 1
          else
            echo "All required files/dirs are present and no intruders found. 🎉"
          fi
