name: Nova Directory Validator

on:
  pull_request:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate each repo-root directory
        run: |
          REQUIRED=(
            "dependency.json"
            "commands"
            "plugins"
            "root.nv"
            "versions.json"
            "priorities.json"
            "extras"
            ".nvroot"
          )

          fail=0

          for dir in */; do
            echo "🔎 Checking $dir ..."
            pushd "$dir" > /dev/null

            # Check required items
            for item in "${REQUIRED[@]}"; do
              if [ ! -e "$item" ]; then
                echo "❌ $dir is missing: $item"
                fail=1
              else
                echo "✅ $dir has: $item"
              fi
            done

            # Check for unknown files/dirs
            for entry in * .*; do
              case "$entry" in
                .|..|.git|.github) continue ;;
                ${REQUIRED[0]}|${REQUIRED[1]}|${REQUIRED[2]}|${REQUIRED[3]}|${REQUIRED[4]}|${REQUIRED[5]}|${REQUIRED[6]})
                  continue ;;
                *)
                  echo "⚠️ $dir contains unknown file/dir: $entry"
                  fail=1
                  ;;
              esac
            done

            popd > /dev/null
          done

          if [ $fail -eq 1 ]; then
            echo "❌ Validation failed: one or more directories are invalid."
            exit 1
          else
            echo "🎉 All root-level directories passed validation!"
          fi
