name: Nova Directory Validator

on:
  pull_request:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate required files and dirs
        id: validate
        run: |
          REQUIRED=(
            "dependency.json"
            "commands"
            "plugins"
            "root.nv"
            "versions.json"
            "priorities.json"
            "extras"
          )

          missing=0
          for item in "${REQUIRED[@]}"; do
            if [ ! -e "$item" ]; then
              echo "❌ Missing: $item"
              missing=1
            else
              echo "✅ Found: $item"
            fi
          done

          unknown=0
          for entry in * .*; do
            case "$entry" in
              .|..|.git|.github) continue ;;
              ${REQUIRED[0]}|${REQUIRED[1]}|${REQUIRED[2]}|${REQUIRED[3]}|${REQUIRED[4]}|${REQUIRED[5]}|${REQUIRED[6]})
                continue ;;
              *)
                echo "⚠️ Unknown file/dir: $entry"
                unknown=1
                ;;
            esac
          done

          if [ $missing -eq 1 ] || [ $unknown -eq 1 ]; then
            echo "Validation failed."
            exit 1
          else
            echo "All good."
          fi

      - name: Enable auto-merge
        if: github.event_name == 'pull_request' && success()
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
